/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minicalculadora;

/**
 *
 * @author alumno
 */
public class MiniCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form MiniCalculadora
     */
    public MiniCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txfNum1 = new javax.swing.JTextField();
        txfNum2 = new javax.swing.JTextField();
        txfResultado = new javax.swing.JTextField();
        comboBox = new javax.swing.JComboBox();
        boton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MINICALCULADORA");

        txfNum1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txfNum1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfNum1.setText("0");

        txfNum2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txfNum2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfNum2.setText("0");

        txfResultado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txfResultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfResultado.setText("0");

        comboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-", "*", "/" }));

        boton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton.setText("=");
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcular(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txfNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txfNum2)
                        .addComponent(boton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txfResultado))
                    .addComponent(comboBox)
                    .addComponent(txfNum1))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcular(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcular
   Numero n1 = new Numero(txfNum1.getText(), ',');
 Numero n2 = new Numero(txfNum2.getText(), ',');
 double num1 = n1.getNumero();
 double num2 = n2.getNumero();
 double resul = 0;
 if (num1 == Double.MAX_VALUE || num2 == Double.MAX_VALUE) {
 txfResultado.setText("error");
 } else {
 String operacion = (String) comboBox.getSelectedItem();
 switch (operacion) {
 case "+":
 resul = num1 + num2;
 break;
 case "-":
 resul = num1 - num2;
 break;
 case "*":
 resul = num1 * num2;
 break;
 case "/":
 if(num2==0){
 resul=Double.MAX_VALUE;
 }else{
 resul = num1 / num2;
 }
 }
 if(resul==Double.MAX_VALUE){
 txfResultado.setText("error");

 }else{
 Numero resultado=new Numero(resul);
 txfResultado.setText(resultado.toString());
 }
 }
 

    }//GEN-LAST:event_calcular

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiniCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiniCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiniCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiniCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiniCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.JComboBox comboBox;
    private javax.swing.JTextField txfNum1;
    private javax.swing.JTextField txfNum2;
    private javax.swing.JTextField txfResultado;
    // End of variables declaration//GEN-END:variables
}
